#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: ${project.version}               #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Placeholders]                                                    #
# https://github.com/montlikadani/TeleportSigns/wiki/Placeholders   #
#                                                                   #
# [Tips]                                                            #
# - Use color coding '&' character, on this page:                   #
# http://minecraft.gamepedia.com/Formatting_codes                   #
# - In case of an error, write here:                                #
# https://github.com/montlikadani/TeleportSigns/issues              #
# - If the string is empty does not send the message.               #
#-----------------------------OOO-----------------------------------#

#=========================================#
#                Settings                 #
#=========================================#
# Options.
options:
  # Log plugin messages into console.
  logconsole: true

  # Sign usage time. (Permission: teleportsigns.use.nocooldown)
  use-cooldown: 5

  # Sign updates in ticks. 20 ticks = 1 second.
  sign-updates: 200

  # How much time do you start the server pinging? (In ticks)
  ping-interval: 30
  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and take the ping interval by one more.
  # How much time does the server pinging down? (In ticks)
  ping-timeout: 29

  # Connection time. (How much time to wait for a player to join and another to wait for him to join the server.)
  # To avoid waiting for the connection time, enter -1 in two places.
  # The plugin rewrites the connection-throttle in bukkit.yml to the number that is in it.
  # The plugin can not be rewritten in BungeeCord.
  connect-timeout: 4000

  # When you break the sign or not find the layout on the sign, drop a sign?
  drop-sign: false

  # Server connection message.
  # Use %newline%, %prefix%, %server% placeholder.
  enter-message: '&6You entered the server&7 %server%&6!'

  # Defines a background of the sign.
  background:
    enable: false
    # Possible types: glass, wool, clay (color depends on motd start color).
    type: glass
    # Block colors.
    block-colors:
      # When the server is online.
      online:
        wool: 5
        glass: 5
        clay: 5
      # When the server is offline.
      offline:
        wool: 14
        glass: 14
        clay: 14
      # When the server loading.
      loading:
        wool: 3
        glass: 11
        clay: 3

# The servers that players join.
servers:
  pvp:
    # Server IP address and port.
    address: '127.0.0.1:25566'
    # Display name that are on the sign.
    displayname: '&6[&cPvP&6]'
  survival:
    # Server IP address and port.
    address: '127.0.0.1:25567'
    # Display name that are on the sign.
    displayname: '&e[&aSurvival&e]'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v${project.version}&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: teleportsigns.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /ts reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'

# DO NOT CHANGE THIS!
config-version: 1
