#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: ${version}                       #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configurations]                                          #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Placeholders]                                                    #
# https://github.com/montlikadani/TeleportSigns/wiki/Placeholders   #
#                                                                   #
# [Tips]                                                            #
# - Use color coding '&' character, on this page:                   #
# http://minecraft.gamepedia.com/Formatting_codes                   #
# - In case of an error, write here:                                #
# https://github.com/montlikadani/TeleportSigns/issues              #
#-----------------------------OOO-----------------------------------#

#=========================================#
#                Settings                 #
#=========================================#
options:
  # Log plugin messages into console.
  logconsole: true

  # Sign usage time. (Permission: teleportsigns.use.nocooldown)
  use-cooldown: 5

  # Sign updates in ticks. 20 ticks = 1 second.
  sign-updates: 200

  # How much time do you start the server pinging? (In ticks)
  ping-interval: 30
  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and take the ping interval by one more.
  # How much time does the server pinging down? (In ticks)
  ping-timeout: 29

  # Connection time. (How much time to wait for a player to join and another to wait for him to join the server.)
  # To avoid waiting for the connection time, enter -1 in two places.
  # The plugin rewrites the connection-throttle in bukkit.yml to the number that is in it.
  # The plugin can not be rewritten in BungeeCord.
  connect-timeout: 4000

  # When you break the sign, drop a sign.
  sign-break-drop: false

  # Server connection message.
  enter-msg-enable: true
  # Use %newline%, %prefix%, %server% placeholder.
  enter-message: '&6You entered the server&7 %server%!'

  # Defines a background of the sign, possible types: glass, wool, clay (color depends on motd start color).
  background-enable: false
  background: glass

# The servers that players join.
servers:
  pvp:
    # Server IP address.
    # Go to your server and enter "/ts checkip" - this will show the ip and port address you need to enter here.
    address: '127.0.0.1:25566'
    displayname: '&6[&cPvP&6]'
  survival:
    # Server IP address.
    # Go to your server and enter "/ts checkip" - this will show the ip and port address you need to enter here.
    address: '127.0.0.1:25567'
    displayname: '&e[&aSurvival&e]'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable-message: true
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v${version}&a!'
plugin-disable-message: true
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: teleportsigns.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /ts reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'
