#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: ${version}                       #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Placeholders]                                                    #
# https://github.com/montlikadani/TeleportSigns/wiki/Placeholders   #
#                                                                   #
# [Tips]                                                            #
# - Use color coding '&' character, on this page:                   #
# http://minecraft.gamepedia.com/Formatting_codes                   #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
# - If the string is empty does not send the message.               #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Log plugin messages into console.
  logconsole: true

  # Sign usage time. (Bypass permission: teleportsigns.use.nocooldown)
  use-cooldown: 5

  # Sign updates in ticks. 20 ticks = 1 second.
  sign-updates: 200

  # How much time do you start the server pinging? (In ticks)
  ping-interval: 30
  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In ticks)
  ping-timeout: 29

  # When you break the sign or not find the layout on the sign, drop a sign?
  drop-sign: false

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Server connection message.
  # Use %newline%, %prefix%, %server% placeholder.
  enter-message: "&6You entered the server&7 %server%&6!"

  # Defines a background of the sign.
  background:
    enable: false
    # Possible types: glass, wool, clay.
    type: glass
    # Block id colors:
    # Glass: https://minecraft.gamepedia.com/Glass#Data_values
    # Wool: https://minecraft.gamepedia.com/Wool#Data_values
    # Clay (Terracotta): https://minecraft.gamepedia.com/Terracotta#Data_values
    block-colors:
      # When the server is online.
      online:
        wool: 5
        glass: 5
        clay: 5
      # When the server is offline.
      offline:
        wool: 14
        glass: 14
        clay: 14
      # When the server loading.
      loading:
        wool: 3
        glass: 11
        clay: 3
      # When the server is full of players.
      full:
        wool: 9
        glass: 9
        clay: 9

# The servers that players join.
servers:
  pvp:
    # Server IP address and port.
    address: "222.0.0.1:25566"
    # Display name that are on the sign.
    displayname: "&6[&cPvP&6]"
  survival:
    # Server IP address and port.
    address: "222.0.0.1:25567"
    # Display name that are on the sign.
    displayname: "&e[&aSurvival&e]"

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TeleportSigns plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v${version}&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 4
