#-----------------------------OOO-----------------------------------#
#                TeleportSigns Configuration File                   #
#-----------------------------OOO-----------------------------------#
# config.yml file. Plugin version: ${version}                       #
# Author, created by: montlikadani                                  #
#-----------------------------OOO-----------------------------------#
# [Default configuration]                                           #
# github.com/montlikadani/TeleportSigns/blob/master/config.yml      #
#                                                                   #
# [Tips]                                                            #
# - If you find a bug, send here:                                   #
# https://github.com/montlikadani/TeleportSigns/issues              #
#-----------------------------OOO-----------------------------------#

# Options
options:
  # Use external server as a hosted server?
  # If false then using internal server.
  external-server: true

  # Log plugin messages into console.
  logconsole: true

  # Sign usage time to prevent twice connect to that server.
  # This will be ignored with this permission: teleportsigns.use.nocooldown
  use-cooldown: 5

  # Sign updates time in ticks.
  # Example: 20 ticks = 1 second
  sign-updates: 200

  # How much time start the server pinging? (In seconds)
  ping-interval: 30

  # Important! If you do not want the pinging to end ping-timeout to be smaller than one and
  # take the ping interval by one more.
  # How much time does the server pinging down? (In seconds)
  ping-timeout: 29

  # Ignoring the player sneaking when clicking on the sign.
  ignore-player-sneaking: true

  # Defines a background of the sign.
  background:
    enable: false

    # Possible types: glass, wool, clay
    type: glass

# The servers that players join.
servers:
  pvp:
    # Server IP address and port.
    address: "222.0.0.1:25566"

    # Display name that are on the sign.
    displayname: "&6[&cPvP&6]"
  survival:
    # Server IP address and port.
    address: "222.0.0.1:25567"

    # Display name that are on the sign.
    displayname: "&e[&aSurvival&e]"

#=========================================#
#             Plugin Settings             #
#=========================================#
# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6[&2Teleport&eSigns&6]&7 >&a The plugin successfully enabled&6 v${version}&a!'
plugin-disable: '&6[&2Teleport&eSigns&6]&7 >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 5
